### ISSUE TITLE
Performance analysis of NCEM Parallel notebooks on multinode (ipyparallel)

### ISSUE THREAD

**Issue by shreddd** [NERSC/Jupyter-Superfacility#2]
IPyParallel
- [x] compare moving data from client to engines using different mechanisms
    - passing data as input to function calling apply() on view (current method)
    - passing data to engines by assignment to view (about the same as passing as input)
    - passing data to engines by calling push() on view (about the same as passing as input)
       - assigning/pushing data to engines also requires a cleanup step to delete or you end up running out of memory
    - reading data from files on SCRATCH instead of passing via network
        - can't load entire dataset per engine or you run out of memory, numpy.load with memmap_mode='r' can work for reading slices, but is not faster than passing the slices as input
- [x] improve scaling performance using ipyparallel with multiple nodes
- [x] test load_balanced_view vs calling engines directly
    - more likely to have out of memory errors with load balanced view, slower to submit
- [x] test making fewer calls per engine with more work
    - this was the key for scaling, 1 call per engine since the controller has a large round trip cost per  call

- [x] profile send vs gather
    - reduced send to less than one second by reducing number of calls and reducing input overhead
    - gather is now the limiting step, will be more difficult to improve because it appears to be limited by ipyparallel controller and infrastructure
- [x] follow up on Steve email suggestions
  - tested serializing static inputs (improved performance)
  - tested serializing datacube (decreased performance)
      - exact times varied by disk and network patterns (using $SCRATCH), but this added about 13 seconds for the test data to serialize, so any gains from the engines didn't matter
  - pickling/unpickling seems to be a factor for ipyparallel

**Comment by mlhenderson** [comment]
Completed all but comparison to Dask, might want to make that a separate issue for tracking

**Comment by mlhenderson** [comment]
Completed
