### ISSUE TITLE
Setup nbviewer for example notebooks

### ISSUE THREAD

**Issue by shreddd** [NERSC/Jupyter-Superfacility#4]
- [x] nbviewer as a service
- [x] nbviewer customizations
- [x] clone notebook through jupyterlab extension + contents API for 
- [x] clone + launch notebook?

**Comment by krinsman** [comment]
Docker example of nbviewer as a service:
https://github.com/krinsman/jupyterhub-deploy

**Comment by krinsman** [comment]
This is also further progress along those lines -- I think this basically already accomplishes all of the checkboxes, but I want to refine it further so as to increase the changes that the corresponding PR is actually accepted by the nbviewer team. E.g. make it less hacky and a more long-term maintainable solution, e.g. more modular/adaptable to other use cases besides our specific one.

https://github.com/krinsman/nbviewer

**Comment by krinsman** [comment]
TODO: internal review of nbviewer PR:
https://github.com/jupyter/nbviewer/compare/master...krinsman:master

cf. implementation of clone notebooks extension: https://github.com/krinsman/notebook-clone-extension/tree/master/clonenotebooks

@shreddd
