### ISSUE TITLE
Resource monitoring extension

### ISSUE THREAD

**Issue by shreddd** [NERSC/Jupyter-Superfacility#9]
People would like something that tells them how much time they have left in the job.  Yeah, they can get this themselves through a terminal or something, but I wonder if we can find a nice way to display this.  It counts as "resource" so we could maybe see about getting something built off Yuvi's status bar thing

**Comment by krinsman** [comment]
https://github.com/krinsman/jupyterlab_resuse

This can obviously be expanded upon, but anyway right now has bar graphs for CPU usage and memory.

**Comment by krinsman** [comment]
For completeness this should also be linked to: https://github.com/krinsman/nbresuse

as well as https://www.npmjs.com/package/jupyterlab-cpustatus
https://github.com/tslaton/jupyterlab-cpustatus
